### ISSUE TITLE
Is there a way to ignore lazy vals?

### ISSUE THREAD

**Issue by siliconsenthil** [gnieh/sohva#35]
Hi,

We're using sohva in project.

In our model case classes, we wish to ignore few attributes from getting persisted. 
We have lazy vals which we don't want them get persisted.

Is there a way to to that?

**Comment by satabin** [comment]
Hi,

I integrated yesterday the change to spray-json as underlying json library, maybe this can solve your problem more easily.
I uploaded this as version 2.0.0-SNAPSHOT  if you want to give it a try.

**Comment by siliconsenthil** [comment]
Thanks @satabin
