### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by ngbinh** [gnieh/sohva#44]
Hi,

I would like to use https://github.com/gnieh/sohva/commit/18d0b35e0fbc7f4f779ad179aee7ab21cc33c1d6 so can you please release a new version?

Thanks

**Comment by satabin** [comment]
I will probably release a new one this week (probably tomorrow).

**Comment by ngbinh** [comment]
Thanks!

**Comment by ngbinh** [comment]
Looks like you have already tag version 1.1.0. Are you waiting to publish it to Maven? The latest version in Maven Central is still 1.0.0 http://mvnrepository.com/artifact/org.gnieh/sohva-client_2.11

Thanks

**Comment by satabin** [comment]
Sorry something went wrong with my signing key. It should now be available within a few hours on central repository.

**Comment by ngbinh** [comment]
Still not there yet. :disappointed:

**Comment by satabin** [comment]
I am not sure how often sonatype repositories are synchronized with maven central but it's here now: http://search.maven.org/#search|ga|1|sohva

**Comment by ngbinh** [comment]
Oh great. Thanks!
