### ISSUE TITLE
Serialization of extended classes

### ISSUE THREAD

**Issue by kelebra** [gnieh/sohva#46]
Hello,

Having the simple code like this:
```
sealed abstract class Model(val _id: ID = System.currentTimeMillis().toString, val _rev: Option[String] = None)
case class User(nickname: String) extends Model
```
and trying to save user instance to database _id field is not taking into account and I get some id generated by couchDb.

As I saw this is more issue of lift-json rather than sohva client, but unfortunately I cannot update lift-json formats to give it a hint regarding User class. Any suggestion on what should I do (override, provide etc.) in order to achieve full-depth serialization of User object?

Thanks in advance.

**Comment by satabin** [comment]
Hi,

Indeed, sohva does not expose the entire lift-json capablities, and only way you can deal with it currently is to write a custom [`SohvaSerializer`](https://github.com/gnieh/sohva/wiki/Custom-Serializers) with your logic in it. Probably something along the lines:

```scala
class MySerializer extends SohvaSerializer[User] {
  def serialize(couchVersion: String): Serializer[User] = new Serializer[User] {
    def serialize(implicit format: Formats): PartialFunction[Any, JValue] =
      ???
    def deserialize(implicit format: Formats): PartialFunction[(TypeInfo, JValue), User] =
      ???
  }
}
```

It is not ideal but I am working on porting sohva to [spray-json](https://github.com/spray/spray-json) for the next version, which will provide the entire capabilities of this library into sohva (see branch [new-json-library](https://github.com/gnieh/sohva/tree/wip/new-json-lib)).
I have been disappointed with the lift-json library lately and the fact that it heavily relies on reflection at runtime.
I hope you can get around with the custom serializer until the new version is available.

**Comment by kelebra** [comment]
Thanks a lot for quick reply.

Yes, but I wanted to mention that actually this approach you mentioned will not give me an opportunity to use another json library as return type of methods still belongs to lift library that will cause additional conversion to this return type.

I ended up with inlining these val's to the case class. As soon as you update your client I will change it, but for now it seems to be the only reasonable solution.

That's really good to know that you still support and update this couch client, as I really like it :)
