### ISSUE TITLE
Does it work with couchbase?

### ISSUE THREAD

**Issue by mushtaq** [gnieh/sohva#62]
Sorry for asking it here, I could not find a google group or some other forum.

**Comment by satabin** [comment]
There is none yet, maybe I should open one :)
I don’t think so, because couchbase has a completely different communication protocol, not HTTP based. The name can be misleading but there is no compatibility between both database APIs.

**Comment by mushtaq** [comment]
Thanks for a quick response. I guess with 2.0 release couchdb has bridged the gap with couchbase, maybe we will consider it. Your driver looks really good. Thanks.
