### ISSUE TITLE
Entities with names only differing in case problems when using SBT assembly on case-insensitive filesystems

### ISSUE THREAD

**Issue by ionos** [gnieh/sohva#77]
Hi,

When building a fat-jar on a Mac (case-insensitive filesystem) using 'sbt assembly', classes that only differ in upper/lower-cases in their fully-qualified name are unzip'ed using the same path during the extraction phase. One of these classes will then be missing in the final jar file.

This affects for example `gnieh/sohva/mango/Sort.class` and `gnieh/sohva/mango/sort.class`.

Would it be possible to rename one of those classes to make Sohva work with 'sbt assembly' on case-insensitive file systems?

Thank you

**Comment by satabin** [comment]
Hi,

I thought case-insensitive fs were something from the past :)
I will see what is best, The first class is from the Mango AST, the second one from the DSL.

**Comment by ionos** [comment]
Works great, verified with custom built package based on master with the fix-77 branch merged in (custom build because of akka-http vs akka-http-experimental dependency issues).

Thanks!

**Comment by satabin** [comment]
I thought I fixed this dependency issue. I will look at it. but first of all let’s merge this one.

**Comment by ionos** [comment]
sorry, my bad: the dependencies are all fine in master. so once this one is merged, you'll have the perfect version for "sbt assembly".

**Comment by satabin** [comment]
I will first publish 2.0.3-SNAPSHOT with the fix. Then cherry-pick the fix to master, I made it the wrong way this time :)

**Comment by satabin** [comment]
OK jars for versions 2.0.3-SNAPSHOT and 2.1.0-SNASPHOT pushed to sonatype snapshot repositories. You can use them now.

**Comment by ionos** [comment]
fantastic, thank you!
