### ISSUE TITLE
In CouchDB 2.3 purge_seq changed from Long to String

### ISSUE THREAD

**Issue by urieli** [gnieh/sohva#97]
In CouchDB 2.3, purge_seq has changed from a `Long` to a `String`.
This breaks the code below from `Database.scala`:

```scala
  def info: Future[Option[InfoResult]] =
    for (info <- couch.optHttp(HttpRequest(uri = uri)) withFailureMessage f"info failed for $uri")
      yield info.map(infoResult)

final case class InfoResult(
    compact_running: Boolean,
    db_name: String,
    disk_format_version: Int,
    disk_size: Long,
    doc_count: Long,
    doc_del_count: Long,
    data_size: Long,
    instance_start_time: String,
    purge_seq: Long,
    update_seq: JsValue,
    sizes: Option[Sizes],
    other: Option[Map[String, JsValue]])
```

If `purge_seq` was changed to a `JsValue`, would we remain compatible with both CouchDB <= 2.2 (Long) and CouchDb >= 2.3 (String)?

**Comment by satabin** [comment]
It would be more consistent with the `update_seq` field, so yes we should change the type to `JsValue`. Can you open a PR?

**Comment by strokyl** [comment]
+1

**Comment by satabin** [comment]
Oh I completely forgot about that PR, let's merge it. I'll publish a new snapshot with it when I'm at home. You will probably need some dependency upgrades PR as well, for akka, right?

**Comment by strokyl** [comment]
@satabin Thank you a lot for you reactivity.
Does you library as some "non unit" test in order to prevent this kind of regression?
If yes could you guide so I could add a test to prevent futur regression on database.info.

Considering your following question:
>  You will probably need some dependency upgrades PR as well, for akka, righ
I don't know yiet maybe @urieli can answer you

**Comment by satabin** [comment]
I don't and I haven't been maintaining this library actively in the last year. The unit tests are flaky as soon as they touch the streaming part, because of how akka streams work and travis infrastructure, I am really not a big fan of them.
